report_title = "Daily Report for"
date_label = "Date"
total_time_label = "Total Time Recorded"
status_label = "Status"
sleep_label = "Sleep"
exercise_label = "Exercise"
getup_time_label = "Getup Time"
remark_label = "Remark"
no_records_message = "No time records for this day."
statistics_label = "Statistics"
all_activities_label = "All Activities"
activity_remark_label = "Activity Remark"
main_font = "Noto Serif SC"
cjk_main_font = "Noto Serif SC"
base_font_size = 12
report_title_font_size = 18
category_title_font_size = 16
margin_in = 1.0
list_top_sep_pt = 0
list_item_sep_ex = -0.5
activity_connector = "->"

[keyword_colors]
study = "#2ECC40"
recreation = "#FF4136"
meal = "#FF851B"
exercise = "#0074D9"
routine = "#AAAAAA"
sleep = "#B10DC9"
code = "#39CCCC"

[[statistics_items]]
label = "Sleep Time"
db_column = "sleep_total_time"
show = true

[[statistics_items]]
label = "Study Time"
db_column = "study_time"
show = true

[[statistics_items]]
label = "Total Exercise Time"
db_column = "total_exercise_time"
show = true

[[statistics_items.sub_items]]
label = "Anaerobic Exercise"
db_column = "anaerobic_time"
show = true

[[statistics_items.sub_items]]
label = "Cardio Exercise"
db_column = "cardio_time"
show = true

[[statistics_items]]
label = "Grooming Time"
db_column = "grooming_time"
show = true

[[statistics_items]]
label = "Recreation Time"
db_column = "recreation_time"
show = true

[[statistics_items.sub_items]]
label = "Zhihu"
db_column = "recreation_zhihu_time"
show = true

[[statistics_items.sub_items]]
label = "Bilibili"
db_column = "recreation_bilibili_time"
show = true

[[statistics_items.sub_items]]
label = "Douyin"
db_column = "recreation_douyin_time"
show = true