build:
  maxIssues: 0

complexity:
  CyclomaticComplexMethod:
    threshold: 20
    excludes: ['**/ui/screen/**']
  LongMethod:
    threshold: 80
    excludes: ['**/ui/screen/**']
  LongParameterList:
    excludes: ['**/ui/screen/**']
  TooManyFunctions:
    thresholdInClasses: 14
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**', '**/ui/**']

naming:
  FunctionNaming:
    functionPattern: '([a-z][a-zA-Z0-9]*|[A-Z][a-zA-Z0-9]*)'
  InvalidPackageDeclaration:
    active: false
  TopLevelPropertyNaming:
    constantPattern: '[A-Za-z][_A-Za-z0-9]*'

style:
  LoopWithTooManyJumpStatements:
    maxJumpCount: 2
    excludes: ['**/ui/**']
  MagicNumber:
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**', '**/*.kts', '**/ui/**']
    ignorePropertyDeclaration: true
  MaxLineLength:
    maxLineLength: 160
    excludes: ['**/ui/**']
  ReturnCount:
    max: 3
    excludes: ['**/ui/**']
  UnusedParameter:
    excludes: ['**/ui/**']
  UnusedPrivateProperty:
    excludes: ['**/ui/**']
