[aliases]
"meal" = "meal_dining"
"吃饭" = "meal_dining"
"饭" = "meal_dining"

"洗澡" = "routine_body-hygiene_bathing"
"洗漱" = "routine_personal-hygiene_oral-hygiene"
"上厕所" = "routine_toilet"
"快递" = "routine_express"

"睡觉" = "sleep_day"
"白天睡觉" = "sleep_day"

"wake" = "sleep_getup"
"w" = "sleep_getup"
"起床" = "sleep_getup"
"醒" = "sleep_getup"
"新的一天开始了" = "sleep_getup"

"rest" = "rest"
"休息" = "rest"
"r" = "rest"
"失眠" = "insomnia"

"zhihu" = "recreation_online-platforms_zhihu"
"知乎" = "recreation_online-platforms_zhihu"
"douyin" = "recreation_online-platforms_douyin"
"抖音" = "recreation_online-platforms_douyin"
"bilibili" = "recreation_online-platforms_bilibili"
"哔哩哔哩" = "recreation_online-platforms_bilibili"
"weibo" = "recreation_online-platforms_weibo"

"minecraft" = "recreation_game_minecraft"
"守望先锋" = "recreation_game_overwatch"
"overwatch" = "recreation_game_overwatch"
"皇室战争" = "recreation_game_clash-royale"
"cr" = "recreation_game_clash-royale"
"Clash Royale" = "recreation_game_clash-royale"

"有氧训练" = "exercise_cardio"
"无氧训练" = "exercise_anaerobic"

"英语单词" = "study_english_words"
"英语写作" = "study_english_writing"
"英语听力" = "study_english_listening"
"英语文章" = "study_english_article"
"高等数学" = "study_math_calculus"
"高等数学二重积分" = "study_math_calculus_double-integral"
"线性代数" = "study_math_linear-algebra"
"线性代数矩阵" = "study_math_linear-algebra_matrix"
"概率统计" = "study_math_probability-theory"
"数据结构" = "study_computer_data_structure"
"数据结构二叉树" = "study_computer_data-structure_trees"
"数据结构图" = "study_computer_data-structure_graphs"
